<a href="https://colab.research.google.com/github/polivio/PEE/blob/master/KNN_KDD_BR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# https://www.kaggle.com/c/kddbr-2019/data

# KNN KDD BR -Polivio
import numpy as np
from sklearn import preprocessing, neighbors
import pandas as pd
from sklearn.model_selection import train_test_split

In [68]:
# preprocessing # blob # raw
train = pd.read_csv('https://github.com/polivio/PEE/raw/master/Training_grouped.csv')
test = pd.read_csv('https://github.com/polivio/PEE/raw/master/Test_grouped.csv')

#df.replace('?', -99999, inplace= True)
#df.drop(['id'] ,1, inplace= True)

train.head()

   Unnamed: 0  ...  traininglabelorder.score
0           2  ...                  0.009647
1           3  ...                  0.842084
2           5  ...                  0.744601
3           6  ...                  0.842084
4           9  ...                  0.944177

[5 rows x 21 columns]

In [69]:
train.columns

Index(['Unnamed: 0', 'traininglabelorder.scatterplotID', 'qtde.ponto',
       'Negative', 'Sample', 'mean.signalX', 'sd.signalX', 'var.signalX',
       'kurtosis.signalX', 'skew.signalX', 'mean.signalY', 'sd.signalY',
       'var.signalY', 'kurtosis.signalY', 'skew.signalY', 'L', 'X', 'XY', 'Y',
       'mean.silhouette', 'traininglabelorder.score'],
      dtype='object')

In [70]:

train = train.loc[:,['traininglabelorder.scatterplotID', 'qtde.ponto', 
       'mean.signalX', 'sd.signalX', 'kurtosis.signalX',
      'mean.signalY', 'sd.signalY', 
       'kurtosis.signalY', 'L', 'X', 'XY', 'Y',
       'mean.silhouette', 'traininglabelorder.score']]



train.head(20)

    traininglabelorder.scatterplotID  ...  traininglabelorder.score
0                                  2  ...                  0.009647
1                                  3  ...                  0.842084
2                                  5  ...                  0.744601
3                                  6  ...                  0.842084
4                                  9  ...                  0.944177
5                                 10  ...                  1.000000
6                                 12  ...                  0.578706
7                                 13  ...                  1.000000
8                                 16  ...                  0.944319
9                                 17  ...                  0.751477
10                                19  ...                  1.000000
11                                20  ...                  0.283536
12                                24  ...                  0.474833
13                                25  ...                  0.647776
14                                26  ...                  0.795196
15                                28  ...                  1.000000
16                                30  ...                  0.006463
17                                33  ...                  0.768378
18                                34  ...                  0.944177
19                                35  ...                  0.745189

[20 rows x 14 columns]

In [71]:
test.columns

Index(['Unnamed: 0', 'testorder.ID', 'qtde.ponto', 'Negative', 'Sample',
       'mean.signalX', 'sd.signalX', 'var.signalX', 'kurtosis.signalX',
       'skew.signalX', 'mean.signalY', 'sd.signalY', 'var.signalY',
       'kurtosis.signalY', 'skew.signalY', 'L', 'X', 'XY', 'Y',
       'mean.silhouette'],
      dtype='object')

In [72]:
test = test.loc[:,['testorder.ID', 'qtde.ponto', 
       'mean.signalX', 'sd.signalX', 'kurtosis.signalX',
      'mean.signalY', 'sd.signalY', 
       'kurtosis.signalY', 'L', 'X', 'XY', 'Y',
       'mean.silhouette']]
test.head(20)

    testorder.ID  qtde.ponto  mean.signalX  ...     XY      Y  mean.silhouette
0              1         384   2929.713542  ...  167.0   94.0         0.916505
1             22         384   1409.484375  ...  189.0   99.0         0.891220
2             27         382   2031.329843  ...   73.0  254.0         0.947689
3             31         370   2900.078378  ...   10.0  185.0         0.954000
4             55         384   2567.598958  ...  182.0   92.0         0.829513
5             78         384   4270.281250  ...  221.0  124.0         0.419574
6             80         373   2978.777480  ...   10.0   91.0         0.896077
7             89         384    757.755208  ...  361.0   10.0         0.858830
8            103         112   1365.607143  ...   36.0   72.0         0.896741
9            104         212   1061.561321  ...   64.0  120.0         0.953351
10           116         375   2603.053333  ...   20.0  216.0         0.952802
11           129         384    468.973958  ...   27.0  188.0         0.897665
12           131         371   1478.663073  ...    NaN   47.0         0.952402
13           133         309   1458.689320  ...    2.0  169.0         0.949457
14           141         384   2747.588542  ...  156.0   77.0         0.890903
15           147         384   1796.411458  ...   18.0  248.0         0.894931
16           149         384    444.885417  ...    4.0  368.0         0.926698
17           158         384   2706.635417  ...  114.0   81.0         0.736624
18           161         384   2722.815104  ...   11.0  181.0         0.921240
19           172         380   2071.052632  ...  192.0   79.0         0.900564

[20 rows x 13 columns]

In [73]:

# https://stackoverflow.com/questions/49420427/pandas-df-fillnadf-mean-not-working-on-multiindex-dataframe

train = train.reset_index()

train = train.fillna(0)
train.head(20)

    index  ...  traininglabelorder.score
0       0  ...                  0.009647
1       1  ...                  0.842084
2       2  ...                  0.744601
3       3  ...                  0.842084
4       4  ...                  0.944177
5       5  ...                  1.000000
6       6  ...                  0.578706
7       7  ...                  1.000000
8       8  ...                  0.944319
9       9  ...                  0.751477
10     10  ...                  1.000000
11     11  ...                  0.283536
12     12  ...                  0.474833
13     13  ...                  0.647776
14     14  ...                  0.795196
15     15  ...                  1.000000
16     16  ...                  0.006463
17     17  ...                  0.768378
18     18  ...                  0.944177
19     19  ...                  0.745189

[20 rows x 15 columns]

In [74]:
train.columns

Index(['index', 'traininglabelorder.scatterplotID', 'qtde.ponto',
       'mean.signalX', 'sd.signalX', 'kurtosis.signalX', 'mean.signalY',
       'sd.signalY', 'kurtosis.signalY', 'L', 'X', 'XY', 'Y',
       'mean.silhouette', 'traininglabelorder.score'],
      dtype='object')

In [75]:
test = test.reset_index()

test = test.fillna(0)
test.head(20)

    index  testorder.ID  qtde.ponto  ...     XY      Y  mean.silhouette
0       0             1         384  ...  167.0   94.0         0.916505
1       1            22         384  ...  189.0   99.0         0.891220
2       2            27         382  ...   73.0  254.0         0.947689
3       3            31         370  ...   10.0  185.0         0.954000
4       4            55         384  ...  182.0   92.0         0.829513
5       5            78         384  ...  221.0  124.0         0.419574
6       6            80         373  ...   10.0   91.0         0.896077
7       7            89         384  ...  361.0   10.0         0.858830
8       8           103         112  ...   36.0   72.0         0.896741
9       9           104         212  ...   64.0  120.0         0.953351
10     10           116         375  ...   20.0  216.0         0.952802
11     11           129         384  ...   27.0  188.0         0.897665
12     12           131         371  ...    0.0   47.0         0.952402
13     13           133         309  ...    2.0  169.0         0.949457
14     14           141         384  ...  156.0   77.0         0.890903
15     15           147         384  ...   18.0  248.0         0.894931
16     16           149         384  ...    4.0  368.0         0.926698
17     17           158         384  ...  114.0   81.0         0.736624
18     18           161         384  ...   11.0  181.0         0.921240
19     19           172         380  ...  192.0   79.0         0.900564

[20 rows x 14 columns]

In [0]:
# change the dtype to 'float64' 
train = train.astype('float64')

In [93]:

X = np.array(train.drop(['traininglabelorder.score'], 1))
y = np.array(train['traininglabelorder.score'])


print(y)

[0.00964712 0.84208443 0.74460145 ... 0.8007374  0.00594233 0.7671597 ]

In [0]:
# https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=10)

# Qual é o parâmetro correto para random_state? e o significado de shuffle?

#X_test = np.array(test.drop(['traininglabelorder.score'], 1))
#y_test = np.array(test['? ]) --> primeira tentativa somente com os dados de treinamento.

In [96]:
# classsifiers KNN

clf = neighbors.KNeighborsRegressor(n_neighbors=4)
clf.fit(X_train , y_train)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
                    metric_params=None, n_jobs=None, n_neighbors=4, p=2,
                    weights='uniform')

In [97]:


accuracy = clf.score(X_test, y_test)

print(accuracy)

-0.11853681911855829

In [0]:
#example_measures = np.array([4,2,1,1,1,2,3,2,1]) 

example_measures = np.array([[4,2,1,1,1,2,3,2,1], [4,2,1,2,2,2,3,2,1]])
example_measures = example_measures.reshape(len(example_measures),-1) 
prediction = clf.predict(example_measures)
print(prediction)

# class 2 = ben 2 4 = maligno

[2 2]